### PR TITLE
refactor: element creation in mounted function

### PR DESCRIPTION
**Pull request by niekvanstaveren**

### CODE REVIEW

**Comment by haxxmaxx** [comment]
So this should fix the problem which would occur if we made a proper release to the client?

**Comment by niekvanstaveren** [comment]
> So this should fix the problem which would occur if we made a proper release to the client?

At the moment there is no problem, but this is what Miralem said about that:

> it’s works today in Sense due to the way we load the extension, but with better caching that might change

**Comment by haxxmaxx** [comment]
> > So this should fix the problem which would occur if we made a proper release to the client?
> 
> At the moment there is no problem, but this is what Miralem said about that:
> 
> > it’s works today in Sense due to the way we load the extension, but with better caching that might change

And this PR addresses that?

**Comment by niekvanstaveren** [comment]
> > > So this should fix the problem which would occur if we made a proper release to the client?
> > 
> > 
> > At the moment there is no problem, but this is what Miralem said about that:
> > > it’s works today in Sense due to the way we load the extension, but with better caching that might change
> 
> And this PR addresses that?

Yes, @miralemd could you explain how this would change things for future caching changes?

**Comment by miralemd** [comment]
There is a problem today already if you were to render more than one button in a mashup.

The exported function is only run once to initiate the supernova type. Things inside `component` is code that runs for every instance, so anything that is instance-based should be inside `component`

```js
export default function supernova() {
  /*
   * This function is only loaded and executed once
   * Any code placed here is to be considered global
   */
  return {
    qae: {},
    component: {}
  };
}
```

**Pull request merged**
