### PR TITLE
chore: format check in ci

### PR DESCRIPTION
**Pull request by niekvanstaveren**

### CODE REVIEW

**Comment by cbt1** [comment]
I don't think we run prettier check on CI on most of our other projects. Why would we need it here?

**Comment by niekvanstaveren** [comment]
> I don't think we run prettier check on CI on most of our other projects. Why would we need it here?

I would say we should probably have it in the other projects as well. Have a PR up for the org chart now as well. Especially in open source projects I think we should try to enforce this (when people do not have prettier setup properly).

**Comment by cbt1** [comment]
> 

I think we just use husky to run estlint before commiting to catch those issues. As this project also has eslint prettier plugin that would work here too.

**Review by cbt1 — APPROVED** [review]
IMO I would go with a pre-commit check instead but if you prefer this solution I'm fine with that

**Comment by niekvanstaveren** [comment]
> IMO I would go with a pre-commit check instead but if you prefer this solution I'm fine with that

Ah right. Yes that sounds better indeed. Thanks 😄

**Pull request merged**
