### PR TITLE
chore: set unit test threshold

### PR DESCRIPTION
**Pull request by niekvanstaveren**

### CODE REVIEW

**Comment by cbt1** [comment]
Looks like this PR is also changing the coverage :oops:, so you might want to update the config file to either include only relevant src files or at least exclude the jest config file

**Comment by cbt1** [comment]
I wonder where coveralls gets that new coverage number from? Look at the coverage reported generated during the build does not produce any that would result in that number from what I can tell

**Comment by niekvanstaveren** [comment]
> I wonder where coveralls gets that new coverage number from? Look at the coverage reported generated during the build does not produce any that would result in that number from what I can tell

No me neither. I'm gonna play a bit locally with this before merging. See if I can get this correct

**Comment by niekvanstaveren** [comment]
> I wonder where coveralls gets that new coverage number from? Look at the coverage reported generated during the build does not produce any that would result in that number from what I can tell

It ended up adding some files to the coverage I think that were not included before. Added some to the excluded path that were only containing constants

**Review by cbt1 — APPROVED** [review]

**Pull request merged**
